---
title: "Which fifteen-minutes neighborhoods are dead-ends? An analysis of the network attributes of fifteen-minute pedsheds"
author:
  - name: Author One
    email: a1@example.com
    affiliation: University One
    correspondingauthor: true
    footnote: 1
  - name: Author Two
    email: a2@example.com
    affiliation: University Two
  - name: Author Three
    email: a3@example.com
    affiliation: University One
    footnote: 2
  - name: Author Four
    email: a4@example.com
    affiliation: University One
    footnote: 2
address:
  - code: University One
    organization: Department
    addressline: 1 main street
    city: City
    state: State
    postcode: 123456
    country: Country
  - code: University Two
    organization: Department
    addressline: 2 main street
    postcode: 2054
    city: City
    country: Country
footnote:
  - code: 1
    text: "This is the first author footnote."
  - code: 2
    text: "Another author footnote."
abstract: |
  Fifteen-minutes neihborhoods, a form of normative chronourbanism based on cumulative opportunities, has aroused interest as a way to reduce the need for motorized travel, and increase the livability, convenience, and health of the public. At the core of this concept is a pedshed, an area defined by the walkable isochrone of the eponymous fifteen minutes. As the idea of fifteen-minutes neighborhoods develops traction in policy and planning circles, it seems timely to revisit the way street network design can support—or obstruct—the stated goal of preserving or creating walkable neighborhoods with essential amenities. In this paper we examine a sample ($n=834$) of fifteen-minutes pedsheds in Hamilton, a medium-sized city in Canada, and how their sizes relate to the attributes of the transportation network. The analysis reveals that network design in suburban Hamilton conspires against the creating of fifteen-minutes neighborhoods. Much of urban Hamilton, in contrast, already has the characteristics of fifteen-minutes neighborhoods. The research points to elements of network design that can help to discriminate between candidate neighborhoods and dead-ends, and that can provide parameters for the design of new developments.

keywords: 
  - Fifteen-minutes neighborhoods
  - Pedshed
  - Walkability
  - Accessibility
  - Network analysis
journal: "Sustainable Cities and Society"
date: "`r Sys.Date()`"
classoption: preprint, 3p, authoryear
bibliography:
  - "`r system('kpsewhich ../bibliography/bibliography.bib', intern=TRUE)`"
linenumbers: false
numbersections: true
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
---

```{r chunk-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```


# Introduction

"Il faut oublier la traversée de Paris d'est en ouest en voiture"^[ "We must forget about crossing Paris from east to west by car"] [@alimi2020]. 

With this declaration during her reelection campaign in 2020, Anne Hidalgo brought international attention to the concept of walkable fifteen-minutes neighborhoods. 


<!-- 
Automotive retrofits in traditional city centers:

@bass2019automotive
-->

@knight2018walkable
@liu2022toward
@pozoukidou2021fifteen
@weng2019fifteen

We address the following research questions:

1. Is there a difference in the transportation network topology between urban and suburban areas within 15-minute walking distances?
2. If such a difference exists, what is its effect on the 15-minute walksheds in terms of accessibility, where accessibility is understood as the provision of opportunities?

# Data

Relevant data to develop this paper comprises to use 15-min pedestrian sheds (or walksehds) classified into urban and suburban types in Hamilton.

15-minute walksheds in the city of Hamilton were obtained by extracting relevant structural attributes of the street network within 15-minute pedestrian sheds. These sheds were calculated for each shed as polygon representations of origin-destination walking time matrices, with a maximum travel time of 15 minutes. Walkshed calculations were generated using the travel_time_matrix function for walking from the {r5r} R package. This process involved defining the street network, as well as the origins and destinations of walking trips. The street network data for these calculations was sourced from OpenStreetMap @OpenStreetMap2023.   
<!--- 
To see the details of the routing see notebook 01-OSM-Network-and-Routing.Rmd in folder data-raw
--->

The origins we established are proxies for the centroids of neighborhoods in the urban and peri-urban areas of the city of Hamilton. Specifically, these are the centroids of Hamilton's Dissemination Areas (DA). A DA is composed of one or more neighboring dissemination blocks and represents the smallest standard geographic area for which all census data are disseminated in Canada. Data on urban and sub-urban boundaries and DAs were retrieved from @HamiltonData2023.

Destinations were established as the centroids of geohashed hexagons within the region of interest, where Hamilton's amenities are located, assuming that presence of amenities is a proxy to provision of opportunities. These destinations were chosen to avoid calculating travel times to each individual amenity. Instead, we used the geohashed polygons as destinations, identifying the amenities within each polygon and assuming that the centroid of each hexagon represents the location of the amenities within it. Specifically, we retrieved geohashing data for Hamilton using the H3 system (SOURCE) and generated child hexagons at resolution 13, with an average area of 43.87 $m^2$. Amenities location and typologies were downloaded from @OpenStreetMap2023.
<!--- 
To see the details of the destinations see notebook 02-OSM-Amenities.Rmd in folder data-raw
--->


# Methods

The proposed method involves studying 15-minute walking neighborhoods in two stages. In the first stage, we assess the accessibility levels of Hamilton's watersheds from a normative perspective, focusing on the provision of opportunities. In the second stage, we characterize the topology urban and suburban walksheds based on a set of network structure attributes. Finally, we analyze the effect of walkshed size on urban and suburban networks, and consequently, on access to opportunities. 

## Calculation of accessibility levels

The indicator we use assesses levels of accessibility from a normative perspective, focusing on reachable opportunities as estimates of the potential for spatial interactions @Hansen1959. The advantage of using this form of accessibility analysis in this study is that it has been shown to be a valuable method for exploring the relationship between transportation infrastructure and urban structure @Handy1997.

In this study, we calculate cumulative accessibility scores by summing the number of amenities within urban and suburban walksheds, categorized into the four types provided by the data source: financial, sustenance, healthcare, and library.
<!--- 
To see the details of the accessibility calculations see notebook 04-Accessibility-Calculations.Rmd in folder data-raw
--->


## Urban and suburban walkshed modelling

### Network attributes by walkshed

In this work we characterize urban and suburban walksheds based on their network structure. As a way to capture and describe the structure of networks we calculate a selection of 12 network structural attributes using the network analysis R package igraph (@IgraphManual). The set of attributes is described as follows @IgraphManual:

- Number of vertices.
- Number of edges.
- Diameter: it is the length of the shortest path between the most distanced nodes in a graph.
- Radius: it is the minimum among all the maximum distances between a vertex to all other vertices.
- Global efficiency: the global efficiency of a network is defined as the average of inverse. distances between all pairs of vertices.´
- Edge density: the density of a graph is the ratio of the actual number of edges and the largest possible number of edges in the graph.
- Mean distance: mean length of all the shortest paths from or to the vertices in the network.
- Girth: the girth of a graph is the length of the shortest cycle in it, being a cycle a non-empty trail in which only the first and last vertices are equal.
- Minimum cut of a graph: the minimum total weight of the edges needed to remove to separate the graph into (at least) two components. 
- Edge connectivity: it is a measure of network vulnerability, minimum number of edges to remove to disconnect two nodes (there is no longer a path between them.
- Transitivity: it is the probability that the neighbors of a node are neighbors between them. 
- Motifs (calculated for 3-node and 4-node sizes): it indicates the presence of particular sub-graphs that repeat themselves. In other words, a graph with a large number of motifs will tend to have few unique elements (some elements happen again, again, and again). A graph with many unique elements will have few motifs (repetitive patterns).
<!--- 
To see the details of the attribute calculations see notebook 03-Network-Attributes-by-Walkshed.Rmd in folder data-raw
--->

### Modelling

To model urban and suburban walksheds, we employ a classification tree approach using the set topology attributes calculated in the previous stage. Classification trees are machine learning techniques used for both regression and classification, widely appreciated in various disciplines for their ability to represent knowledge through decision rules, making them easy to interpret and analyze @Loh2011 @James2013 @Paez2019Trees. Specifically, we utilize evolutionary trees, a variant of decision trees that are less constrained by the limitations of greedy top-down induction algorithms @Cha2009 @Kretowski2007 @Grubinger2014. Since evolutionary trees use a genetic algorithm that introduces randomness in the initial conditions, we run the model from the R package evtree @Grubinger2014 with 20 random seeds to identify the network variables that consistently characterize urban and suburban walksheds.

Finally we 

<!--- 
To see the details of walkshed profile calculations see notebook 06-Walkshed-Profiles.Rmd in folder data-raw
--->

## Walkshed size in urban and suburban areas


# References {-}

